import { useState, useRef, useEffect } from "react";
import EventSource from "react-native-sse";
import { askAgent } from "../../lib/aiCoach/ask";
import { fetchConversationHistory, deleteConversation as deleteConversationApi } from "../../lib/aiCoach/chats";
import { createWorkout } from "../../lib/models/workout";
import { addRestDay } from "../../lib/models/restDays";
import { updateGoal } from "../../lib/models/goals";
import { LIMITS } from "../../lib/constants";

export interface Message {
    id: string;
    type: "user_message" | "ai_message" | "status" | "tool_call" | "error";
    text?: string;
    tool?: string;
    args?: Record<string, any>;
    result?: any;
    status?: "pending" | "approved" | "rejected";
    completed?: boolean;
}

export function useAIChat() {
    const [messages, setMessages] = useState<Message[]>([]);
    const [conversationTitle, setConversationTitle] = useState("");
    const [conversationId, setConversationId] = useState<string | null>(null);
    const eventSourceRef = useRef<EventSource | null>(null);

    // Clean up EventSource on unmount
    useEffect(() => {
        return () => {
            if (eventSourceRef.current) {
                eventSourceRef.current.close();
            }
        };
    }, []);

    const startAgentStream = async (text: string, continueConversation: boolean = false) => {
        if (eventSourceRef.current) {
            eventSourceRef.current.close();
        }

        console.log("Starting agent stream with text:", text);

        const es = await askAgent(text, conversationId, {
            onConversationId: (id, title) => {
                if (title) setConversationTitle(title);
                if (id) setConversationId(id);
            },
            onStatus: (message) => {
                setMessages(prev => [
                    ...prev,
                    {
                        id: Date.now().toString() + Math.random(),
                        type: "status",
                        text: message
                    }
                ]);
            },
            onToolCall: (tool, args) => {
                setMessages(prev => [
                    ...prev,
                    {
                        id: Date.now().toString() + Math.random(),
                        type: "tool_call",
                        tool,
                        args,
                        completed: false
                    }
                ]);
            },
            onToolResult: (tool, result) => {
                const isWriteTool = ["create_workout", "mark_rest_day", "set_goal"].includes(tool);
                setMessages(prev => {
                    const newMessages = [...prev];
                    for (let i = newMessages.length - 1; i >= 0; i--) {
                        if (newMessages[i].type === "tool_call" && newMessages[i].tool === tool && !newMessages[i].completed) {
                            newMessages[i] = { 
                                ...newMessages[i], 
                                completed: true,
                                result,
                                status: isWriteTool ? "pending" : undefined 
                            };
                            break;
                        }
                    }
                    return newMessages;
                });
            },
            onFinalResponse: (text) => {
                setMessages(prev => [
                    ...prev,
                    {
                        id: Date.now().toString() + Math.random(),
                        type: "ai_message",
                        text
                    }
                ]);
                eventSourceRef.current = null;
            },
            onError: (message) => {
                setMessages(prev => [
                    ...prev,
                    {
                        id: Date.now().toString() + Math.random(),
                        type: "error",
                        text: message || "An error occurred."
                    }
                ]);
                eventSourceRef.current = null;
            }
        }, continueConversation);

        eventSourceRef.current = es;
    };

    const userMessageCount = messages.filter(m => m.type === "user_message").length;

    const sendMessage = async (text: string) => {
        if (userMessageCount >= LIMITS.AI_CHAT_MESSAGES) return;

        // Add message to state
        const newMessage: Message = {
            id: Date.now().toString(),
            text,
            type: "user_message"
        };
        
        setMessages(prev => [...prev, newMessage]);
        
        // If it's the first message, set the title
        if (messages.length === 0) {
            setConversationTitle("New Conversation"); // Would realistically be generated by AI
        }
        
        await startAgentStream(text, false);
    };

    const approveTool = async (msgId: string) => {
        const msg = messages.find(m => m.id === msgId);
        if (!msg || !msg.tool || !msg.result) return;
        
        try {
            if (msg.tool === "create_workout") {
                await createWorkout({
                    date: msg.result.date,
                    duration: msg.result.duration,
                    totalSkips: msg.result.total_skips,
                    avgSkipsPerMinute: msg.result.avg_skips_per_minute,
                    trips: msg.result.trips,
                    calories: msg.result.calories,
                    heartRateAvg: msg.result.heart_rate_avg,
                    heartRateMax: msg.result.heart_rate_max,
                    notes: msg.result.notes
                });
            } else if (msg.tool === "mark_rest_day") {
                await addRestDay(msg.result.date);
            } else if (msg.tool === "set_goal") {
                await updateGoal(msg.result.updated_goal, msg.result.new_value);
            }

            setMessages(prev => prev.map(m => m.id === msgId ? { ...m, status: "approved" } : m));
            
            // Continue conversation with agent after tool approval
            await startAgentStream("", true);
        } catch (err) {
            console.error("Failed to apply changes to local database:", err);
            setMessages(prev => prev.map(m => m.id === msgId ? { ...m, status: "rejected" } : m));
        }
    };

    const rejectTool = (msgId: string) => {
        setMessages(prev => prev.map(m => m.id === msgId ? { ...m, status: "rejected" } : m));
    };

    const selectConversation = async (id: string, title: string) => {
        setConversationId(id);
        setConversationTitle(title);
        // Clear messages while we load the new ones
        setMessages([]);

        try {
            const history = await fetchConversationHistory(id);
            if (!history) return;
            const formattedMessages: Message[] = history.messages.reduce((acc: Message[], msg, index) => {
                if (msg.role === "tool" || msg.role === "function") {
                    return acc;
                }

                if (msg.tool_calls && Array.isArray(msg.tool_calls)) {
                    msg.tool_calls.forEach((tc, tcIndex) => {
                        acc.push({
                            id: `tc-${msg.id || Date.now()}-${index}-${tcIndex}`,
                            type: "tool_call",
                            tool: tc.name,
                            args: tc.args,
                            completed: true
                        });
                    });
                }

                if (msg.content) {
                    acc.push({
                        id: `msg-${msg.id || Date.now()}-${index}`,
                        type: msg.role === "user" ? "user_message" : "ai_message",
                        text: msg.content,
                    });
                }

                return acc;
            }, []);

            setMessages(formattedMessages);
        } catch {
            setMessages([{
                id: Date.now().toString(),
                type: "error",
                text: "Failed to load conversation history."
            }]);
        }
    };

    const clearChat = () => {
        setMessages([]);
        setConversationTitle("");
        setConversationId(null);
    };

    const deleteConversation = async () => {
        if (conversationId) {
            await deleteConversationApi(conversationId);
        }
        setMessages([]);
        setConversationTitle("");
        setConversationId(null);
    };

    return {
        messages,
        userMessageCount,
        conversationTitle,
        conversationId,
        startAgentStream,
        sendMessage,
        approveTool,
        rejectTool,
        selectConversation,
        clearChat,
        deleteConversation
    };
}
