import React, { useState, useCallback, useRef, useEffect } from "react";
import { View, Text, StyleSheet, ScrollView, KeyboardAvoidingView, Platform, SafeAreaView, ActivityIndicator } from "react-native";
import { useFocusEffect } from "expo-router";
import { getUserProfile, saveUserProfile, type UserProfile } from "../../lib/database";
import AIConsentModal from "../components/AIConsentModal";
import Button from "../components/Button";
import { Ionicons } from "@expo/vector-icons";
import AIChatHeader from "../components/AIChatHeader";
import AIPromptSuggestions from "../components/AIPromptSuggestions";
import AIChatInput from "../components/AIChatInput";
import EventSource from "react-native-sse";
import Animated, { FadeInDown } from "react-native-reanimated";

interface Message {
    id: string;
    type: "user_message" | "ai_message" | "status" | "tool_call" | "error";
    text?: string;
    tool?: string;
    args?: Record<string, any>;
    completed?: boolean;
}

const getToolDisplayInfo = (toolName: string) => {
    switch (toolName) {
        case "get_workouts":
            return { title: "Fetching Workouts", icon: "calendar" as const };
        case "get_workout_details":
            return { title: "Fetching Workout Details", icon: "barbell" as const };
        case "get_streaks":
            return { title: "Checking Streaks", icon: "flame" as const };
        case "get_goals":
            return { title: "Checking Goals", icon: "trophy" as const };
        case "get_chart_data":
            return { title: "Generating Chart Data", icon: "bar-chart" as const };
        default:
            return { title: `Using tool: ${toolName}`, icon: "build" as const };
    }
};

const formatToolArgs = (args: Record<string, any> | undefined) => {
    if (!args || Object.keys(args).length === 0) return null;

    const formattedArgs: string[] = [];

    for (const [key, value] of Object.entries(args)) {
        let displayValue = value;
        let displayKey = key.replace(/_/g, " ");
        
        displayKey = displayKey.charAt(0).toUpperCase() + displayKey.slice(1);

        if ((key === "date_from" || key === "date_to") && typeof value === "string") {
            try {
                const date = new Date(value);
                if (!isNaN(date.getTime())) {
                    displayValue = date.toLocaleDateString(undefined, {
                        month: "short",
                        day: "numeric",
                        year: "numeric"
                    });
                }
            } catch (e) {}
        }

        if (key === "metric" && typeof value === "string") {
            displayValue = value.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
        }

        formattedArgs.push(`${displayKey}: ${displayValue}`);
    }

    return formattedArgs.join(" • ");
};

export default function AIScreen() {
    const [user, setUser] = useState<UserProfile | null>(null);
    const [modalVisible, setModalVisible] = useState(false);
    
    // Chat state
    const [messages, setMessages] = useState<Message[]>([]);
    const [conversationTitle, setConversationTitle] = useState("");
    
    const scrollViewRef = useRef<ScrollView>(null);
    const eventSourceRef = useRef<EventSource | null>(null);

    // Clean up EventSource on unmount
    useEffect(() => {
        return () => {
            if (eventSourceRef.current) {
                eventSourceRef.current.close();
            }
        };
    }, []);

    useFocusEffect(
        useCallback(() => {
            loadProfile();
        }, [])
    );

    const loadProfile = async () => {
        const profile = await getUserProfile();
        setUser(profile);
    };

    const handleConsent = async () => {
        if (user) {
            await saveUserProfile(user.name, user.email || undefined, user.image || undefined, true);
            await loadProfile();
        }
        setModalVisible(false);
    };

    const handleSendMessage = async (text: string) => {
        // Add message to state
        const newMessage: Message = {
            id: Date.now().toString(),
            text,
            type: "user_message"
        };
        
        setMessages(prev => [...prev, newMessage]);
        
        // If it's the first message, set the title
        if (messages.length === 0) {
            setConversationTitle("New Conversation"); // Would realistically be generated by AI
        }
        
        if (eventSourceRef.current) {
            eventSourceRef.current.close();
        }

        const es = new EventSource("https://jumprope-api.vercel.app/ask-agent", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({ message: text })
        });

        eventSourceRef.current = es;

        es.addEventListener("message", (event: any) => {
            if (!event.data) return;

            try {
                const data = JSON.parse(event.data);
                
                setMessages(prev => {
                    const newMessages = [...prev];
                    
                    if (data.type === "status") {
                        newMessages.push({
                            id: Date.now().toString() + Math.random(),
                            type: "status",
                            text: data.message
                        });
                    } else if (data.type === "tool_call") {
                        newMessages.push({
                            id: Date.now().toString() + Math.random(),
                            type: "tool_call",
                            tool: data.tool,
                            args: data.args,
                            completed: false
                        });
                    } else if (data.type === "tool_result") {
                        for (let i = newMessages.length - 1; i >= 0; i--) {
                            if (newMessages[i].type === "tool_call" && newMessages[i].tool === data.tool && !newMessages[i].completed) {
                                newMessages[i] = { ...newMessages[i], completed: true };
                                break;
                            }
                        }
                    } else if (data.type === "final_response") {
                        newMessages.push({
                            id: Date.now().toString() + Math.random(),
                            type: "ai_message",
                            text: data.text
                        });
                        es.close();
                        eventSourceRef.current = null;
                    } else if (data.type === "error") {
                        newMessages.push({
                            id: Date.now().toString() + Math.random(),
                            type: "error",
                            text: data.message || "An error occurred."
                        });
                        es.close();
                        eventSourceRef.current = null;
                    }
                    
                    return newMessages;
                });
            } catch (err) {
                console.error("Failed to parse SSE event data:", err);
            }
        });

        es.addEventListener("error", (error: any) => {
            console.error("SSE error:", error);
            // Ignore connection close events disguised as errors during normal operations
            if (error && error.type === "error" && error.message && error.message.includes("closed")) {
                return;
            }
            
            setMessages(prev => [
                ...prev, 
                {
                    id: Date.now().toString() + Math.random(),
                    text: "Sorry, I encountered an error communicating with the server.",
                    type: "error"
                }
            ]);
            
            if (eventSourceRef.current) {
                eventSourceRef.current.close();
                eventSourceRef.current = null;
            }
        });
    };

    const handleHistoryPress = () => {
        // Mock function for opening past conversations
        console.log("History pressed");
    };

    const handleClearConversation = () => {
        setMessages([]);
        setConversationTitle("");
    };

    if (!user?.ai_enabled) {
        return (
            <View style={styles.containerCenter}>
                <View style={styles.emptyStateContainer}>
                    <View style={styles.iconContainer}>
                        <Ionicons name="sparkles" size={48} color="#ccfa53" />
                    </View>
                    <Text style={styles.emptyStateTitle}>AI Coach</Text>
                    <Text style={styles.emptyStateSubtitle}>
                        Your personal jump rope coach, powered by Gemini. Get 
                        personalized workout insights and goals.
                    </Text>
                    <Button 
                        title="Enable AI Features" 
                        onPress={() => setModalVisible(true)} 
                        variant="primary"
                    />
                </View>

                <AIConsentModal
                    visible={modalVisible}
                    onCancel={() => setModalVisible(false)}
                    onConsent={handleConsent}
                />
            </View>
        );
    }

    // Main AI Chat Interface
    return (
        <SafeAreaView style={styles.container}>
            <AIChatHeader title={conversationTitle} onHistoryPress={handleHistoryPress} onClearConversation={handleClearConversation} />
            
            <ScrollView 
                style={styles.chatArea}
                contentContainerStyle={[
                    styles.chatContent,
                    messages.length === 0 && styles.chatContentEmpty
                ]}
                ref={scrollViewRef}
                onContentSizeChange={() => scrollViewRef.current?.scrollToEnd({ animated: true })}
            >
                {messages.length === 0 ? (
                    <View style={styles.greetingContainer}>
                        <View style={styles.greetingHeader}>
                            <View style={styles.geminiIcon}>
                                <Ionicons name="sparkles" size={32} color="#ffffff" />
                            </View>
                            <Text style={styles.greetingHello}>Hello, <Text style={styles.greetingName}>{user.name}!</Text></Text>
                            <Text style={styles.greetingQuestion}>How can I assist{"\n"}you today?</Text>
                        </View>
                        
                        <AIPromptSuggestions onSelectOption={handleSendMessage} />
                    </View>
                ) : (
                    <View style={styles.messagesList}>
                        {messages.map((msg, index) => {
                            const isLatest = index === messages.length - 1;
                            
                            if (msg.type === "user_message" || msg.type === "ai_message") {
                                return (
                                    <Animated.View 
                                        key={msg.id} 
                                        entering={FadeInDown.duration(400).springify()}
                                        style={[
                                            styles.messageBubble,
                                            msg.type === "user_message" ? styles.messageUser : styles.messageAI
                                        ]}
                                    >
                                        <Text style={styles.messageText}>{msg.text}</Text>
                                    </Animated.View>
                                );
                            } else if (msg.type === "status") {
                                return (
                                    <Animated.View key={msg.id} entering={FadeInDown.duration(400).springify()} style={styles.statusContainer}>
                                        {isLatest ? (
                                            <ActivityIndicator size="small" color="#ccfa53" style={styles.statusIcon} />
                                        ) : (
                                            <Ionicons name="checkmark-circle" size={14} color="#a0a0a0" style={styles.statusIcon} />
                                        )}
                                        <Text style={styles.statusText}>{msg.text}</Text>
                                    </Animated.View>
                                );
                            } else if (msg.type === "tool_call") {
                                const toolInfo = getToolDisplayInfo(msg.tool || "");
                                const formattedArgs = formatToolArgs(msg.args);

                                return (
                                    <Animated.View key={msg.id} entering={FadeInDown.duration(400).springify()} style={styles.toolCallCard}>
                                        <View style={styles.toolCallHeader}>
                                            <Ionicons name={toolInfo.icon} size={18} color="#ff5526" />
                                            <Text style={styles.toolCallTitle}>{toolInfo.title}</Text>
                                            {msg.completed ? (
                                                <Ionicons name="checkmark-circle" size={18} color="#ccfa53" style={styles.toolCallStatusIcon} />
                                            ) : (
                                                <ActivityIndicator size="small" color="#ccfa53" style={[styles.toolCallStatusIcon, { transform: [{ scale: 0.8 }] }]} />
                                            )}
                                        </View>
                                        {formattedArgs && (
                                            <View style={styles.toolCallArgsContainer}>
                                                <Text style={styles.toolCallArgsText}>{formattedArgs}</Text>
                                            </View>
                                        )}
                                    </Animated.View>
                                );
                            } else if (msg.type === "error") {
                                return (
                                    <Animated.View key={msg.id} entering={FadeInDown.duration(400).springify()} style={styles.errorCard}>
                                        <Ionicons name="alert-circle" size={20} color="#ff5526" />
                                        <Text style={styles.errorText}>{msg.text}</Text>
                                    </Animated.View>
                                );
                            }
                            return null;
                        })}
                    </View>
                )}
            </ScrollView>

            <AIChatInput onSend={handleSendMessage} />
        </SafeAreaView>
    );
}

const styles = StyleSheet.create({
    containerCenter: {
        flex: 1,
        backgroundColor: "#0a0a0a",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    container: {
        flex: 1,
        backgroundColor: "#0a0a0a",
    },
    emptyStateContainer: {
        alignItems: "center",
        maxWidth: 320,
    },
    iconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "rgba(204, 250, 83, 0.1)",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 24,
    },
    emptyStateTitle: {
        fontSize: 28,
        fontWeight: "700",
        color: "#ffffff",
        marginBottom: 16,
        textAlign: "center",
    },
    emptyStateSubtitle: {
        fontSize: 16,
        color: "#a0a0a0",
        textAlign: "center",
        marginBottom: 32,
        lineHeight: 24,
    },
    chatArea: {
        flex: 1,
    },
    chatContent: {
        padding: 20,
        paddingBottom: 40,
    },
    chatContentEmpty: {
        flexGrow: 1,
        justifyContent: "center",
    },
    greetingContainer: {
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    greetingHeader: {
        alignItems: "center",
        marginBottom: 20,
    },
    geminiIcon: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: "#10a37f", // Greenish gradient look from design
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 16,
    },
    greetingHello: {
        fontSize: 22,
        color: "#a0a0a0",
        fontWeight: "400",
        marginBottom: 8,
    },
    greetingName: {
        color: "#ffffff",
        fontWeight: "600",
    },
    greetingQuestion: {
        fontSize: 32,
        fontWeight: "800",
        color: "#ffffff",
        textAlign: "center",
        lineHeight: 38,
    },
    messagesList: {
        gap: 16,
    },
    messageBubble: {
        maxWidth: "85%",
        padding: 14,
        borderRadius: 20,
    },
    messageUser: {
        alignSelf: "flex-end",
        backgroundColor: "#ff5526",
        borderBottomRightRadius: 4,
    },
    messageAI: {
        alignSelf: "flex-start",
        backgroundColor: "rgba(255, 255, 255, 0.1)",
        borderBottomLeftRadius: 4,
    },
    messageText: {
        color: "#ffffff",
        fontSize: 16,
        lineHeight: 22,
    },
    statusContainer: {
        flexDirection: "row",
        alignItems: "center",
        alignSelf: "center",
        marginVertical: 4,
    },
    statusIcon: {
        marginRight: 6,
    },
    statusText: {
        color: "#a0a0a0",
        fontSize: 12,
        fontStyle: "italic",
    },
    toolCallCard: {
        backgroundColor: "#1a1a1a",
        borderRadius: 16,
        padding: 16,
        marginVertical: 4,
        alignSelf: "flex-start",
        width: "85%",
        borderWidth: 1,
        borderColor: "rgba(255, 255, 255, 0.05)",
    },
    toolCallHeader: {
        flexDirection: "row",
        alignItems: "center",
    },
    toolCallTitle: {
        color: "#ffffff",
        fontSize: 14,
        fontWeight: "600",
        marginLeft: 8,
        flex: 1,
    },
    toolCallStatusIcon: {
        marginLeft: 8,
    },
    toolCallArgsContainer: {
        backgroundColor: "rgba(0,0,0,0.2)",
        borderRadius: 8,
        padding: 8,
        marginTop: 12,
    },
    toolCallArgsText: {
        color: "#a0a0a0",
        fontSize: 12,
        fontFamily: Platform.OS === "ios" ? "Menlo" : "monospace",
    },
    errorCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "rgba(255, 85, 38, 0.15)",
        borderRadius: 16,
        padding: 16,
        marginVertical: 4,
        alignSelf: "center",
        width: "85%",
        borderWidth: 1,
        borderColor: "rgba(255, 85, 38, 0.3)",
    },
    errorText: {
        color: "#ff5526",
        fontSize: 14,
        fontWeight: "600",
        marginLeft: 8,
        flex: 1,
    },
});
